# Generated by Django 4.1.5 on 2023-01-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agence', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
